### PR TITLE
Fix phpunit.xml.dist

### PR DESCRIPTION
**Pull request by sbani**
Fix the path to the `TestListener`. It's in vendor path for application

### CODE REVIEW

**Comment by sbani** [comment]
updated testsuite paths too

**Comment by mbessolov** [comment]
Hi @sbani,

Can you please elaborate more on the testsuite path changes?
For example, there are no `../src/*/Tests/` paths in this application.

Thank you

**Comment by sbani** [comment]
Hi @mbessolov,

i will show you my setup which should be an ordinary setup for a symfony project:

One `AppBundle` where I have my "own" application code and some more bundles which mostly extend the oro bundles or could be reusable in other projects.
([see Symfony Docs](http://symfony.com/doc/current/best_practices/creating-the-project.html#application-bundles)).

```bash
$ tree -L 2 -d src/
src/
├── AddressBundle
│   ├── Migrations
│   ├── Resources
│   └── Tests
├── AppBundle
│   ├── Command
│   ├── Controller
│   ├── DependencyInjection
│   ├── Entity
│   ├── EventListener
│   ├── Form
│   ├── Mailer
│   ├── Migrations
│   ├── Model
│   ├── Provider
│   ├── Resources
│   ├── Tests
│   └── Twig
├── FileManagerBundle
│   ├── Controller
│   └── Resources
└── UIBundle
    └── Resources
```

**Comment by sbani** [comment]
do you have any questions regarding this issue?

**Comment by DimaSoroka** [comment]
Thanks @sbani, looks clear, we will process this PR shortly

**Comment by zebimax** [comment]
Hi, @sbani. Thank you very much for your contribution! Your PR was merged to development branch.

**Pull request merged**
